name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: project name
      run: image="${{ github.event.repository.name }}"
    - name: extract version for pom.xml
      run: version="$(grep -oPm2 "(?<=<version>)[^<]+" pom.xml | sed -n 2p)"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$version
      
      
        
        

    
    
    
        

