name: tagging-workflow

on:
  workflow_dispatch:

env:
  CONTAINER_REGISTRY: ghcr.io

jobs:
  tagging:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, "release")
    steps:
#     소스 체크아웃
    - uses: actions/checkout@v2
    
#     저장소이름 추출
    - name: PROJECT_NAME Exctract
      run: echo "PROJECT_NAME=$(echo $GITHUB_REPOSITORY|cut -d '/' -f 2)" >> $GITHUB_ENV

#     브랜치 추출
    - name: RELEASE_VERSION Exctract
      run: echo "RELEASE_VERSION=$(echo $GITHUB_REF_NAME|cut -d '/' -f 2)-RC" >> $GITHUB_ENV

#     소스 버전 추출
    - name: SOURCE_VERSION Exctract
      run: echo "SOURCE_VERSION=$(grep -oPm2 "(?<=<version>)[^<]+" pom.xml | sed -n 2p)" >> $GITHUB_ENV

#     도커 로그인
    - name: Docker Login
      uses: docker/login-action@v1.12.0
      with:
        registry: ${{ env.CONTAINER_REGISTRY }}
#         danawalab 계정에선 토큰이 안보임..
        username: joonwoo8888
        password: ${{ secrets.CR_TOKEN }}

#     이미지 태그
    - name: Docker Tag
      run: docker tag ${{ env.CONTAINER_REGISTRY }}/$GITHUB_REPOSITORY:${{ env.RELEASE_VERSION }} ${{ env.CONTAINER_REGISTRY }}/$GITHUB_REPOSITORY:${{ env.SOURCE_VERSION }} 
